[project]
name = "fastflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ignite>=1.1.0",
    "matplotlib>=3.9.4",
    "numpy<2",
    "pyyaml<=6.0",
    "scikit-image>=0.24.0",
    "torch<=1.9.1",
]
