[project]
name = "fastflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "opencv-python>=4.13.0.90",
    "scikit-image>=0.24.0",
]
