circle:
  x: 3571
  y: 1583
  min_radius: 170
  max_radius: 190
  screw_ratio: 0.62

detection:
  param1: 30
  param2: 40
  min_dist: 20

images:
  supported_formats:
    - .jpg
    - .jpeg
    - .png
