circle:
  x: 3571
  y: 1583
  min_radius: 165
  max_radius: 190
  screw_ratio: 0.62

detection:
  param1: 100
  param2: 25
  min_dist: 30

images:
  supported_formats:
    - .jpg
    - .jpeg
    - .png
