circle:
  x: 3571
  y: 1583
  min_radius: 170
  max_radius: 190
  screw_ratio: 0.65

detection:
  param1: 50
  param2: 30
  min_dist: 50

images:
  supported_formats:
    - .jpg
    - .jpeg
    - .png
